name: Go

# Controls when the workflow will run
on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        go get -v -t -d ./...
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o api
        tar -czf release-$RELEASE_VERSION.api.tar.gz api

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: api
        path: api

    # Create Release v1
    - name: Make Release
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          release-$RELEASE_VERSION.api.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}